version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.1
    environment:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      TAKE_FILE_OWNERSHIP: 1
      discovery.type: single-node
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - elasticsearch

  logstash:
    image: dcm4che/logstash-dcm4chee:7.6.0-10
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "12201:12201/udp"
      - "8514:8514/udp"
      - "8514:8514"
    depends_on:
      - elasticsearch
    volumes:
      - ./dcm4chee-arc/logstash/filter-hashtree:/usr/share/logstash/data/filter-hashtree
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.48-22.1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: slapd
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - ./dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - ./dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:9.0.2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: keycloak
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      KEYCLOAK_WAIT_FOR: ldap:389 logstash:8514
    depends_on:
      - ldap
      - logstash
    volumes:
      - ./dcm4chee-arc/keycloak:/opt/keycloak/standalone
  keycloak-gatekeeper:
    image: dcm4che/keycloak-gatekeeper:9.0.2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: keycloak-gatekeeper
    ports:
      - "8643:8643"
    environment:
      PROXY_LISTEN: :8643
      PROXY_REDIRECTION_URL: https://localhost:8643
      PROXY_UPSTREAM_URL: http://kibana:5601
      PROXY_DISCOVERY_URL: https://localhost:8843/auth/realms/dcm4che
      PROXY_CLIENT_ID: kibana
      PROXY_CLIENT_SECRET: 968956a3-582b-4f8c-9d09-249fc9f74c35
      PROXY_ENCRYPTION_KEY: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
    command:
      - "--openid-provider-timeout=120s"
      - "--tls-cert=/etc/certs/cert.pem"
      - "--tls-private-key=/etc/certs/key.pem"
      - "--skip-openid-provider-tls-verify=true"
      - "--enable-refresh-tokens=true"
      - "--resources=uri=/*|roles=auditlog"
    depends_on:
      - kibana
      - keycloak
  db:
    image: dcm4che/postgres-dcm4chee:11.2-16
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: postgres
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    depends_on:
      - logstash
    volumes:
      - ./dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.22.1-secure
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: dcm4chee-arc
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514
    depends_on:
      - ldap
      - keycloak
      - db
      - logstash
    volumes:
      - ./dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - ./dcm4chee-arc/storage:/storage