version: "3"
services:
  keycloak:
    image: dcm4che/keycloak:9.0.2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://<elk-node>:12201"
        tag: keycloak
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTP_PORTS: 8993
      KEYCLOAK_WAIT_FOR: <db-node>:389 <elk-node>:8514
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.22.1-secure
    logging:
      driver: gelf
      options:
        gelf-address: "udp://<elk-node>:12201"
        tag: dcm4chee-arc
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: <db-node>:389 <db-node>:5432 <elk-node>:8514
    depends_on:
      - keycloak
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage
  keycloak-gatekeeper:
    image: dcm4che/keycloak-gatekeeper:9.0.2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://<elk-node>:12201"
        tag: keycloak-gatekeeper
    ports:
      - "8643:8643"
    environment:
      PROXY_LISTEN: :8643
      PROXY_REDIRECTION_URL: https://<arc-node>:8643
      PROXY_UPSTREAM_URL: http://kibana:5601
      PROXY_DISCOVERY_URL: https://keycloak:8843/auth/realms/dcm4che
      PROXY_CLIENT_ID: kibana
      PROXY_CLIENT_SECRET: 968956a3-582b-4f8c-9d09-249fc9f74c35
      PROXY_ENCRYPTION_KEY: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
    command:
      - "--openid-provider-timeout=120s"
      - "--tls-cert=/etc/certs/cert.pem"
      - "--tls-private-key=/etc/certs/key.pem"
      - "--skip-openid-provider-tls-verify=true"
      - "--enable-refresh-tokens=true"
      - "--resources=uri=/*|roles=auditlog"
    depends_on:
      - keycloak