version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.48-22.1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://elk-node:12201"
        tag: slapd
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:12.2-22
    logging:
      driver: gelf
      options:
        gelf-address: "udp://elk-node:12201"
        tag: postgres
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data